---
apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name : MLmodels
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/rewrite-target : /invocations
spec :
  ingressClassName: nginx
  rules :
  - http :
      paths :
      - path : /mlflow/digit-classification-model
        pathType: Exact
        backend :
          service:
            name : mlflow
            port :
              number: 8080